-- MySQL Script generated by MySQL Workbench
-- Tue Feb  4 16:19:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema socialdaw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema socialdaw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `socialdaw` DEFAULT CHARACTER SET utf8 ;
USE `socialdaw` ;

-- -----------------------------------------------------
-- Table `socialdaw`.`categoria_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialdaw`.`categoria_post` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socialdaw`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialdaw`.`rol` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socialdaw`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialdaw`.`usuario` (
  `login` VARCHAR(50) NOT NULL,
  `password` VARCHAR(200) NULL,
  `rol_id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `email` VARCHAR(80) NULL,
  PRIMARY KEY (`login`),
  INDEX `fk_usuario_rol_idx` (`rol_id` ASC),
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`rol_id`)
    REFERENCES `socialdaw`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socialdaw`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialdaw`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `resumen` VARCHAR(500) NULL,
  `texto` MEDIUMTEXT NULL,
  `foto` VARCHAR(100) NULL,
  `categoria_post_id` INT NOT NULL,
  `usuario_login` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_categoria_post1_idx` (`categoria_post_id` ASC),
  INDEX `fk_post_usuario1_idx` (`usuario_login` ASC),
  CONSTRAINT `fk_post_categoria_post1`
    FOREIGN KEY (`categoria_post_id`)
    REFERENCES `socialdaw`.`categoria_post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_usuario1`
    FOREIGN KEY (`usuario_login`)
    REFERENCES `socialdaw`.`usuario` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socialdaw`.`like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialdaw`.`like` (
  `post_id` INT NOT NULL,
  `usuario_login` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`post_id`, `usuario_login`),
  INDEX `fk_post_has_usuario_usuario1_idx` (`usuario_login` ASC),
  INDEX `fk_post_has_usuario_post1_idx` (`post_id` ASC),
  CONSTRAINT `fk_post_has_usuario_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `socialdaw`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_has_usuario_usuario1`
    FOREIGN KEY (`usuario_login`)
    REFERENCES `socialdaw`.`usuario` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socialdaw`.`comenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialdaw`.`comenta` (
  `post_id` INT NOT NULL,
  `usuario_login` VARCHAR(50) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `texto` MEDIUMTEXT NULL,
  PRIMARY KEY (`post_id`, `usuario_login`, `fecha`),
  INDEX `fk_post_has_usuario_usuario2_idx` (`usuario_login` ASC),
  INDEX `fk_post_has_usuario_post2_idx` (`post_id` ASC),
  CONSTRAINT `fk_post_has_usuario_post2`
    FOREIGN KEY (`post_id`)
    REFERENCES `socialdaw`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_has_usuario_usuario2`
    FOREIGN KEY (`usuario_login`)
    REFERENCES `socialdaw`.`usuario` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socialdaw`.`sigue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialdaw`.`sigue` (
  `usuario_login_seguidor` VARCHAR(50) NOT NULL,
  `usuario_login_seguido` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`usuario_login_seguidor`, `usuario_login_seguido`),
  INDEX `fk_usuario_has_usuario_usuario2_idx` (`usuario_login_seguido` ASC),
  INDEX `fk_usuario_has_usuario_usuario1_idx` (`usuario_login_seguidor` ASC),
  CONSTRAINT `fk_usuario_has_usuario_usuario1`
    FOREIGN KEY (`usuario_login_seguidor`)
    REFERENCES `socialdaw`.`usuario` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_usuario_usuario2`
    FOREIGN KEY (`usuario_login_seguido`)
    REFERENCES `socialdaw`.`usuario` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'socialdaw' IDENTIFIED BY 'socialpass';

GRANT ALL ON `socialdaw`.* TO 'socialdaw';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `socialdaw`.`categoria_post`
-- -----------------------------------------------------
START TRANSACTION;
USE `socialdaw`;
INSERT INTO `socialdaw`.`categoria_post` (`id`, `descripcion`) VALUES (0, 'anime');
INSERT INTO `socialdaw`.`categoria_post` (`id`, `descripcion`) VALUES (1, 'jpop');
INSERT INTO `socialdaw`.`categoria_post` (`id`, `descripcion`) VALUES (2, 'kpop');

COMMIT;


-- -----------------------------------------------------
-- Data for table `socialdaw`.`rol`
-- -----------------------------------------------------
START TRANSACTION;
USE `socialdaw`;
INSERT INTO `socialdaw`.`rol` (`id`, `descripcion`) VALUES (0, 'Usuario registrado');
INSERT INTO `socialdaw`.`rol` (`id`, `descripcion`) VALUES (1, 'Administrador');

COMMIT;

